version: "3"
services:
  app:
    container_name: backend-template
    build: .
    restart: always
    environment:
      DB_CONNECTION_STRING: 'mysql://root:hackme@mysql-db:3306/chete_db'
    ports:
      - "8080:8080"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/opt/node_app
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 ./lib/index
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    volumes:
      - my-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user_db'
      MYSQL_PASS: 'user_pwd'
      MYSQL_DATABASE: granite_db
volumes:
  my-data:
  notused: